app:
    resource: "@AppBundle/Controller/"
    type:     annotation

homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index}

search:
    path:     /search/{q}
    defaults: { _controller: AppBundle:Default:search}
